create table tbl_select(
SNO NUMBER NOT NULL PRIMARY KEY ,
BNO NUMBER,
user_ID VARCHAR2(50) NOT NULL,
stype varchar2(50),
SELECTCHECK NUMBER DEFAULT 0 NOT NULL,
SELECTDATE DATE DEFAULT SYSDATE NOT NULL,
FOREIGN KEY (user_ID) REFERENCES tb_user(user_ID) ON DELETE CASCADE,
FOREIGN KEY (BNO) REFERENCES tbl_BOARD (BNO) ON DELETE CASCADE 
);

보드테이블에 selectCnt 추가할것